sudo: false
language: rust

stages:
  - check
  - test
  - nightly

jobs:
  allow_failures:
    - nightly
  fast_finish: true
  include:
    - stage: check
      name: rustfmt
      os: linux
      rust: 1.39.0
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - name: "clippy-and-warnings"
      env: RUSTFLAGS="-D warnings"
      os: linux
      rust: 1.39.0
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all-features -- -D clippy::all
        - cargo test --verbose
    - stage: nightly
      name: nightly
      os: linux
      rust: nightly
      script:
        - cargo test --verbose

rust:
  - 1.39.0  # Oldest supported
  - stable

os:
  - linux
  - osx
  - windows

script:
  - cargo test --verbose

cache:
  cargo: true
