language: rust
os: linux
dist: bionic

stages:
  - check
  - test
  - nightly

jobs:
  allow_failures:
    rust: nightly
  fast_finish: true
  include:

    - stage: check
      name: rustfmt
      rust: 1.42.0
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - name: "clippy-and-warnings"
      env: RUSTFLAGS="-D warnings"
      rust: 1.42.0
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all-features --benches --bins --examples --tests -- -D clippy::all

    - stage: test
      rust: 1.39.0  # Oldest supported
    - rust: stable
    - os: windows
      rust: stable
    - os: osx
      rust: stable

    - stage: nightly
      name: nightly
      rust: nightly

script:
  - cargo test

cache:
  cargo: true
